# Generated by Django 6.1.1 on 2026-09-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_areas_of_interest_userprofile_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
