# Generated by Django 6.1.1 on 2026-10-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_portfolio_url_userprofile_resume_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_scan_reset_date',
            field=models.DateField(auto_now_add=True, default='2026-10-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolios_scanned_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resumes_scanned_this_month',
            field=models.IntegerField(default=0),
        ),
    ]
