@echo off
echo Deleting old virtual environment...
rmdir /s /q venv
echo Creating new virtual environment...
python -m venv venv
echo Activating new virtual environment...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Running database migrations...
python manage.py migrate
echo Starting server...
python manage.py runserver
