# Generated by Django 5.2.17 on 2026-09-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_atsresult_detailed_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='doc_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('portfolio', 'Portfolio')], default='resume', max_length=10),
        ),
    ]
